# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/togeek/svn/trunk/python3/CommonJobScheduler/ui\dialogNewjobCron.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogNewjobCron(object):
    def setupUi(self, DialogNewjobCron):
        DialogNewjobCron.setObjectName("DialogNewjobCron")
        DialogNewjobCron.resize(485, 353)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogNewjobCron)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxJobFile = QtWidgets.QGroupBox(DialogNewjobCron)
        self.groupBoxJobFile.setObjectName("groupBoxJobFile")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxJobFile)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayoutJobFile = QtWidgets.QGridLayout()
        self.gridLayoutJobFile.setObjectName("gridLayoutJobFile")
        self.horizontalLayout.addLayout(self.gridLayoutJobFile)
        self.verticalLayout.addWidget(self.groupBoxJobFile)
        self.groupBoxCondition = QtWidgets.QGroupBox(DialogNewjobCron)
        self.groupBoxCondition.setObjectName("groupBoxCondition")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxCondition)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_1 = QtWidgets.QLabel(self.groupBoxCondition)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_2.addWidget(self.label_1)
        self.lineEditYear = QtWidgets.QLineEdit(self.groupBoxCondition)
        self.lineEditYear.setObjectName("lineEditYear")
        self.horizontalLayout_2.addWidget(self.lineEditYear)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBoxCondition)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEditMonth = QtWidgets.QLineEdit(self.groupBoxCondition)
        self.lineEditMonth.setObjectName("lineEditMonth")
        self.horizontalLayout_3.addWidget(self.lineEditMonth)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBoxCondition)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEditDay = QtWidgets.QLineEdit(self.groupBoxCondition)
        self.lineEditDay.setObjectName("lineEditDay")
        self.horizontalLayout_4.addWidget(self.lineEditDay)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.groupBoxCondition)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.lineEditWeek = QtWidgets.QLineEdit(self.groupBoxCondition)
        self.lineEditWeek.setObjectName("lineEditWeek")
        self.horizontalLayout_7.addWidget(self.lineEditWeek)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.labelDayOfWeek = QtWidgets.QLabel(self.groupBoxCondition)
        self.labelDayOfWeek.setObjectName("labelDayOfWeek")
        self.horizontalLayout_8.addWidget(self.labelDayOfWeek)
        self.lineEditDayOfWeek = QtWidgets.QLineEdit(self.groupBoxCondition)
        self.lineEditDayOfWeek.setObjectName("lineEditDayOfWeek")
        self.horizontalLayout_8.addWidget(self.lineEditDayOfWeek)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.groupBoxCondition)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.lineEditHour = QtWidgets.QLineEdit(self.groupBoxCondition)
        self.lineEditHour.setObjectName("lineEditHour")
        self.horizontalLayout_10.addWidget(self.lineEditHour)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.groupBoxCondition)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.lineEditMinute = QtWidgets.QLineEdit(self.groupBoxCondition)
        self.lineEditMinute.setObjectName("lineEditMinute")
        self.horizontalLayout_11.addWidget(self.lineEditMinute)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.groupBoxCondition)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.lineEditSecond = QtWidgets.QLineEdit(self.groupBoxCondition)
        self.lineEditSecond.setObjectName("lineEditSecond")
        self.horizontalLayout_12.addWidget(self.lineEditSecond)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.checkBoxStartDate = QtWidgets.QCheckBox(self.groupBoxCondition)
        self.checkBoxStartDate.setObjectName("checkBoxStartDate")
        self.horizontalLayout_13.addWidget(self.checkBoxStartDate)
        self.dateTimeEditStartDate = QtWidgets.QDateTimeEdit(self.groupBoxCondition)
        self.dateTimeEditStartDate.setEnabled(False)
        self.dateTimeEditStartDate.setObjectName("dateTimeEditStartDate")
        self.horizontalLayout_13.addWidget(self.dateTimeEditStartDate)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.verticalLayout.addWidget(self.groupBoxCondition)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogNewjobCron)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogNewjobCron)
        QtCore.QMetaObject.connectSlotsByName(DialogNewjobCron)

    def retranslateUi(self, DialogNewjobCron):
        _translate = QtCore.QCoreApplication.translate
        DialogNewjobCron.setWindowTitle(_translate("DialogNewjobCron", "创建Cron类型作业"))
        self.groupBoxJobFile.setTitle(_translate("DialogNewjobCron", "作业脚本文件"))
        self.groupBoxCondition.setTitle(_translate("DialogNewjobCron", "作业条件"))
        self.label_1.setText(_translate("DialogNewjobCron", "Year"))
        self.lineEditYear.setToolTip(_translate("DialogNewjobCron", "“年”条件（语法请参考“这是什么”）"))
        self.lineEditYear.setWhatsThis(_translate("DialogNewjobCron", "<html><head/><body><p>a: 表示a年</p><p>*: 表示所有年份</p><p>*/a: 表示所有年份中每过a年一次</p><p>a-b: 表示从a年到b年</p><p>a-b/c: 表示从a年到b年中每过c年一次</p><p>x,y,z,...: 表示多种满足条件的年份，逗号分开的每个条件都可以是以上表达式之一</p></body></html>"))
        self.label_2.setText(_translate("DialogNewjobCron", "Month"))
        self.lineEditMonth.setToolTip(_translate("DialogNewjobCron", "“月”条件（语法请参考“这是什么”）"))
        self.lineEditMonth.setWhatsThis(_translate("DialogNewjobCron", "<html><head/><body><p>a: 表示a月，取值为1至12</p><p>*: 表示所有月份</p><p>*/a: 表示所有月份中每过a月一次</p><p>a-b: 表示从a月到b月</p><p>a-b/c: 表示从a月到b月中每过c月一次</p><p>x,y,z,...: 表示多种满足条件的月份，逗号分开的每个条件都可以是以上表达式之一</p></body></html>"))
        self.label_3.setText(_translate("DialogNewjobCron", "Day"))
        self.lineEditDay.setToolTip(_translate("DialogNewjobCron", "“日”条件（语法请参考“这是什么”）"))
        self.lineEditDay.setWhatsThis(_translate("DialogNewjobCron", "<html><head/><body><p>a: 表示a日，取值为1至31</p><p>*: 表示所有日期</p><p>*/a: 表示所有日期中每过a天一次</p><p>a-b: 表示从a日到b日</p><p>a-b/c: 表示从a日到b日中每过c日一次</p><p>xrd y: 表示本月中第x个星期y，y取值为sun,mon,tue,wed,thu,fri,sat</p><p>last: 表示本月的最后一天</p><p>last x: 表示本月最后一个星期x，x取值为sun,mon,tue,wed,thu,fri,sat</p><p>x,y,z,...: 表示多种满足条件的日期，逗号分开的每个条件都可以是以上表达式之一</p></body></html>"))
        self.label_4.setText(_translate("DialogNewjobCron", "Week"))
        self.lineEditWeek.setToolTip(_translate("DialogNewjobCron", "“周”条件（语法请参考“这是什么”）"))
        self.lineEditWeek.setWhatsThis(_translate("DialogNewjobCron", "<html><head/><body><p>a: 表示第a周，取值为1至53</p><p>*: 表示所有周</p><p>*/a: 表示所有周中每过a周一次</p><p>a-b: 表示从a周到b周</p><p>a-b/c: 表示从a周到b周中每过c周一次</p><p>x,y,z,...: 表示多种满足条件的周，逗号分开的每个条件都可以是以上表达式之一</p></body></html>"))
        self.labelDayOfWeek.setText(_translate("DialogNewjobCron", "Day of week"))
        self.lineEditDayOfWeek.setToolTip(_translate("DialogNewjobCron", "“天（周内）”条件（语法请参考“这是什么”）"))
        self.lineEditDayOfWeek.setWhatsThis(_translate("DialogNewjobCron", "<html><head/><body><p>a: 表示星期a，取值为0至6或者sun,mon,tue,wed,thu,fri,sat</p><p>*: 表示每周内所有的天</p><p>*/a: 表示周中每过a天一次</p><p>a-b: 表示从星期a到星期b</p><p>a-b/c: 表示从星期a到星期b中每过c天一次</p><p>x,y,z,...: 表示多种满足条件的天，逗号分开的每个条件都可以是以上表达式之一</p></body></html>"))
        self.label_6.setText(_translate("DialogNewjobCron", "Hour"))
        self.lineEditHour.setToolTip(_translate("DialogNewjobCron", "“小时”条件（语法请参考“这是什么”）"))
        self.lineEditHour.setWhatsThis(_translate("DialogNewjobCron", "<html><head/><body><p>a: 表示a点，取值为0至23</p><p>*: 表示每个小时</p><p>*/a: 表示每过a小时一次</p><p>a-b: 表示从a点到b点</p><p>a-b/c: 表示从a点到b点中每过c小时一次</p><p>x,y,z,...: 表示多种满足条件的小时，逗号分开的每个条件都可以是以上表达式之一</p></body></html>"))
        self.label_7.setText(_translate("DialogNewjobCron", "Minute"))
        self.lineEditMinute.setToolTip(_translate("DialogNewjobCron", "“分钟”条件（语法请参考“这是什么”）"))
        self.lineEditMinute.setWhatsThis(_translate("DialogNewjobCron", "<html><head/><body><p>a: 表示a分，取值为0至59</p><p>*: 表示每分钟</p><p>*/a: 表示每过a分钟一次</p><p>a-b: 表示从a分到b分</p><p>a-b/c: 表示从a分到b分中每过c分钟一次</p><p>x,y,z,...: 表示多种满足条件的分钟，逗号分开的每个条件都可以是以上表达式之一</p></body></html>"))
        self.label_8.setText(_translate("DialogNewjobCron", "Second"))
        self.lineEditSecond.setToolTip(_translate("DialogNewjobCron", "“秒”条件（语法请参考“这是什么”）"))
        self.lineEditSecond.setWhatsThis(_translate("DialogNewjobCron", "<html><head/><body><p>a: 表示a秒，取值为0至59</p><p>*: 表示每秒钟</p><p>*/a: 表示每过a秒钟一次</p><p>a-b: 表示从a秒到b秒</p><p>a-b/c: 表示从a秒到b秒中每过c秒一次</p><p>x,y,z,...: 表示多种满足条件的秒，逗号分开的每个条件都可以是以上表达式之一</p></body></html>"))
        self.checkBoxStartDate.setToolTip(_translate("DialogNewjobCron", "是否使用“起始时间”条件"))
        self.checkBoxStartDate.setText(_translate("DialogNewjobCron", "Start Date"))
        self.dateTimeEditStartDate.setToolTip(_translate("DialogNewjobCron", "“起始时间”条件"))

